version: "3"
services:
    bot:
        build: ./src
        env_file: ./src/.env
        container_name: discord-bot
        ports:
            - "25921:25921"
        networks:
            - src_net
        restart: unless-stopped
networks:
    src_net:
        driver: bridge